version: 1.1

stages:
  - stage:
    - git-checkout:
        params:
          depth: 1

  - stage:
    - js:
        params:
          workdir: ${git-checkout}
          container_type: spa
          build_cmd: npm run build
          dest_dir: public

  - stage:
    - release:
        params:
          erda_yml: ${git-checkout}/erda.yml
          image:
            erda-site: ${js:OUTPUT:image}

  - stage:
    - erda:
        params:
          release_id_path: ${release}
